# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: tiger
    oracleucp:
      max-pool-size: 50
      max-statements: 200
      min-pool-size: 10
    type: oracle.ucp.jdbc.PoolDataSourceImpl
